apiVersion: v1
kind: Service
metadata:
  name: resultserver-service
spec:
  type: NodePort
  selector:
    app: resultserver
  ports:
  - port: 80 #servis portu
    targetPort: 80 #pod portu
    nodePort: 30002 #portun disa acilan bacagi
 