apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultserver
spec:
  selector:
    matchLabels:
      app: resultserver
  template:
    metadata:
      labels:
        app: resultserver
    spec:
      containers:
      - name: resultserver
        image: bekirkocabas/resultserver
        resources:
        envFrom:
          - secretRef:
              name: mysql-secret
          - configMapRef:
              name: phonebook-cm
        # env:
        #   - name: MYSQL_DATABASE_HOST
        #     value: mysql-service
        #   - name: MYSQL_DATABASE
        #     value: phonebook
        #   - name: MYSQL_USER
        #     value: clarus 
        #   - name: MYSQL_PASSWORD
        #     value: #<mysqlpasswrd>
        ports:
        - containerPort: 80

