apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  type: NodePort
  selector:
    app: webserver
  ports:
  - port: 80 #servis portu
    targetPort: 80 #pod portu
    nodePort: 30001 #portun disa acilan bacagi