//aws_access_key = ""
//aws_secret_key = ""
myami = "ami-026ebd4cfe2c043b2"
mykey = "clarus"
tags = ["postgresql", "nodejs", "react"]
instancetype = ["t2.micro", "t2.micro", "t3a.medium"]
controlinstancetype = "t3a.medium"
num = 3
region = "us-east-1"
mysecgr = "ansible-project-207-sec-gr"
user = "clarusway"