version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: bekir
      MYSQL_PASSWORD: Bekir_123
    networks:
      - bekirnet
  myapp:
    image: bekirkocabas/bookstoreapi:latest
    container_name: myapp
    restart: always
    depends_on:
      - database 
    ports:
      - "80:80"
    networks:
      - bekirnet

networks:
  bekirnet:
    driver: bridge




  

